### ISSUE TITLE
New site job fails to complete with connection refused

### ISSUE THREAD

**Issue by joshuarestivo** [frappe/helm#205]
Chart Version:  6.0.96 and 7.0.70 w/ default image tags

Using the chart's createSite functionality to deploy a site on a fresh install, the site deploys fine and the new-site job runs and shows as Completed. However, looking at the logs for the related pod, it reports:

pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'erpnext-xyz-mariadb' ([Errno 111] Connection refused)")

If I subsequently run a helm upgrade with the exact same values but set forceCreate to true, it creates the site successfully. It's acting like a race condition where the new-site job isn't waiting on the database to be available. This is a pretty simple deployment on a single-node cluster. Mariadb is installed by the chart. I've experienced this with both 6.0.96 and 7.0.70 versions of the chart.Here are the relevant values being used (the only thing not shown is the ingress):

--
persistence:
  enabled: true
  worker:
    storageClass: erpnext-efs

jobs:
  configure:
    fixVolume: false
  createSite:
    enabled: true
    siteName: [REMOVED]
    adminPassword: [REMOVED]
    installApps: ["erpnext"]
    forceCreate: true

mariadb:
  enabled: true
  auth:
    rootPassword: [REMOVED]
    username: site-admin
    password:  [REMOVED]
    replicationPassword: [REMOVED]

**Comment by joshuarestivo** [comment]
Just ran through this again and now I'm not experiencing the issue on 7.0.70. I'm not sure what changed but it must have been on my side. Closing.

**Comment by joshuarestivo** [comment]
Reopening as this is definitely an intermittent issue, which goes along with the notion of a race condition.

**Comment by revant** [comment]
make sure the db service is up and running before create site is executed.
disable create site during first run. Let the services start. Add the job once everything is up and running.

**Comment by MohammedNoureldin** [comment]
I also see the same issue.

The main issue is actually that the job "create site" exists with code 0 even if the database does not exist, while it creates some files apparently.

Here the job should make sure that the database is reachable before trying to write files, and exist with error code, so that the job can be restarted.

**Comment by revant** [comment]
@MohammedNoureldin change this file and https://github.com/frappe/helm/blob/main/erpnext/templates/job-create-site.yaml send a pull request. Add check, wait-for-it command is available in container. I assumed bench new-site will exit with appropriate exit code. You can `set -e` or make sure it exits.

We don't face race conditions in github actions/workflow tests.

**Comment by MohammedNoureldin** [comment]
Thanks @revant for the information.

I have seen the issue multiple times today, nevertheless after a few changes, which unfortunately I did not document, I cannot reproduce the issue.

I will keep an eye on this and create the necessary Pull Request if I could reproduce the issue.

Anyway, I will probably implement this soon though, because as mentioned the container exists with the code 0, whatever its real state is, which can make the issues hard to track.
