### ISSUE TITLE
Support ReadWriteOnce

### ISSUE THREAD

**Issue by clayrisser** [frappe/helm#78]
When I deploy it tries to create a PVC using ReadWriteMany, but my cluster only supports ReadWriteOnce. Can someone explain why ReadWriteMany is required, and any ways I can get around it.

**Comment by revant** [comment]
Install NFS client or server provisioner. That will add a RWX storage class based on NFS server.

RWX is needed because erpnext-python, 3 workers, frappe-socketio and erpnext-nginx containers need to mount common `sites` volume with read write access to the directory. It is required because frappe stores configs, in the volume and dynamically changes the configs through bench_helper command.

If config was read-only then we can use configmaps. We still need common read-write vol for multiple containers to store and upload user files.

I'll close this because right now it is not possible out of the box in framework to use ReadWriteOnce only.
