### ISSUE TITLE
mariadb config

### ISSUE THREAD

**Issue by mashkovd** [frappe/helm#89]
Hello, 
I install mariadb by https://helm.erpnext.com/prepare-kubernetes/mariadb.html
Use master.config and slave.config like in url above and after install bitnami/mariadb with helm i see the next -
no folder 
![Screenshot_20210620_222726](https://user-images.githubusercontent.com/1842423/122685856-b4d67880-d216-11eb-8671-1b677c01b01a.png)

and i found my.cnf in path _/opt/bitnami/mariadb/conf_
![Screenshot_20210620_222844](https://user-images.githubusercontent.com/1842423/122685881-e94a3480-d216-11eb-9ee3-f9308a1767cd.png)

but i's not contain right cnf which i write in values-production.yaml file when install mariadb.

I try reinstall mariadb and now have this problem.

**Comment by mashkovd** [comment]
i found next 
it is need to repalce (https://helm.erpnext.com/prepare-kubernetes/mariadb)
```$ wget -c https://raw.githubusercontent.com/bitnami/charts/master/bitnami/mariadb/values-production.yaml```
to
```$ wget -c https://raw.githubusercontent.com/bitnami/charts/master/bitnami/mariadb/values.yaml```

it have different config (config->configuration)

and now I have 
```pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'10.112.131.170' (using password: YES)")```
in container which create-site

**Comment by revant** [comment]
Generally this community expects spoon fed, blindly copy paste-able code. That's the reason I had written the initial docs. I tried to copy docs from docker, kubernetes, bitnami Mariadb just because people who've never even know what containerisation can start using kubernetes.

The resources like Ingress and batch job api has moved from beta to v1. Bitnami values have changed.

I'm really helpless here now.
No one (more than 95%) really has any idea about anything happening that they've been told to copy paste.

Yesterday I read a long conversation in telegram group where such "ceo" was trying to make some copy-pasta work without even knowing what is happening.

I am out of ideas to help the community who thinks world doesn't exist outside ERPNext

**Comment by revant** [comment]
Done with the rant. Now let's begin a long conversation which probably no one will ever read in future.

By looking at the new values file, lot of things are different.
It is using standalone setup instead of replication.

Configuration is now under different key as you mentioned.

That means each time you install Mariadb, it'll be really great if the official documentation is referred instead of the copy paste approach.

Same goes with other dependencies like NFS, redis, ingress controller

**Comment by revant** [comment]
If you can help me please. Then please update the documentation if you find anything missing.

Please help me.

**Comment by shinzuco** [comment]
@revant I would love to help.

**Comment by revant** [comment]
@shinzuco thank you for offering help!

Can you send PR to gh-pages branch that will update documentation to lates kubernetes api, CronJob, Job and Ingress needs update I think.

For Helm chart docs, I think it should just link to respective official docs. That way our doc doesn't become obsolete when the dependency doc changes.
Do mention a disclaimer to check the official docs of respective projects and not to depend on the copy of that docs here.

**Comment by revant** [comment]
#90 will improve the documentation, for getting the mariadb helm chart up and running refer the official bitnami/mariadb documentation. We need to use this custom cnf, https://github.com/frappe/bench/wiki/MariaDB-conf-for-Frappe in any type of mariadb installation.
